column transformer:

In [1]:
import pandas as pd 
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

step 1: train test split

In [10]:
df=pd.read_csv('covid_toy.csv')
df.sample(5)

age  gender  fever   cough       city has_covid
89   46    Male  103.0  Strong  Bangalore        No
45   72    Male   99.0    Mild  Bangalore        No
52   47  Female  100.0  Strong  Bangalore       Yes
15   70    Male  103.0  Strong    Kolkata       Yes
51   11  Female  100.0  Strong    Kolkata       Yes

In [12]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)
x_train.shape,x_test.shape


((80, 5), (20, 5))

method 1:aam zindagi(without column traansform)

In [17]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [25]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

here fever is a numerical column but have missing values so ham transfromation lagaynge ispe SimpleImputer ye missing value ki jagha mean fill kar dega


In [ ]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.transform(x_test[['fever']])

x_train_fever

array([[ 99.       ],
       [ 98.       ],
       [101.       ],
       [100.       ],
       [ 98.       ],
       [100.       ],
       [100.5890411],
       [101.       ],
       [101.       ],
       [102.       ],
       [104.       ],
       [ 98.       ],
       [ 99.       ],
       [101.       ],
       [ 98.       ],
       [104.       ],
       [101.       ],
       [101.       ],
       [100.5890411],
       [102.       ],
       [100.5890411],
       [101.       ],
       [104.       ],
       [ 98.       ],
       [100.5890411],
       [101.       ],
       [103.       ],
       [102.       ],
       [100.       ],
       [103.       ],
       [100.       ],
       [100.       ],
       [ 98.       ],
       [ 99.       ],
       [104.       ],
       [103.       ],
       [101.       ],
       [100.       ],
       [102.       ],
       [102.       ],
       [ 99.       ],
       [100.       ],
       [100.       ],
       [104.       ],
       [102.       ],
       [10

In [34]:
# ordinalencoding-->cough
oe=OrdinalEncoder()
x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.transform(x_test[['cough']])
x_train_cough


array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [44]:
# OneHotEncoder-->city,gender
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city=ohe.transform(x_test[['gender','city']])
x_train_gender_city #first column is of gender then other three is for city 
x_test_gender_city.shape

(20, 4)

In [45]:
# extracting age 
x_train_age=x_train.drop(columns=['gender','city','fever','cough']).values

x_test_age=x_test.drop(columns=['gender','city','fever','cough']).values

x_train_age,x_test_age.shape

(array([[60],
        [83],
        [64],
        [47],
        [65],
        [10],
        [82],
        [47],
        [51],
        [ 5],
        [25],
        [80],
        [59],
        [49],
        [73],
        [44],
        [20],
        [68],
        [79],
        [49],
        [34],
        [15],
        [56],
        [40],
        [38],
        [19],
        [46],
        [74],
        [55],
        [60],
        [19],
        [ 5],
        [24],
        [25],
        [17],
        [48],
        [ 8],
        [11],
        [33],
        [20],
        [72],
        [19],
        [13],
        [18],
        [82],
        [83],
        [34],
        [26],
        [ 5],
        [66],
        [11],
        [54],
        [12],
        [10],
        [23],
        [65],
        [82],
        [69],
        [81],
        [38],
        [80],
        [69],
        [19],
        [81],
        [84],
        [23],
        [31],
        [14],
        [71],
        [65],
        [22],
      

In [46]:
print(x_test_cough.shape)
print(x_test_age.shape)
print(x_test_fever.shape)
print(x_test_gender_city.shape)

print(x_train_age.shape)
print(x_train_cough.shape)
print(x_train_gender_city.shape)
print(x_train_fever.shape)


(20, 1)
(20, 1)
(20, 1)
(20, 4)
(80, 1)
(80, 1)
(80, 4)
(80, 1)


In [47]:
# concatinating all the columns
x_train_transformed=np.concatenate((x_train_age,x_train_cough,x_train_gender_city,x_train_fever),axis=1)

x_test_transformed=np.concatenate((x_test_age,x_test_cough,x_test_gender_city,x_test_fever),axis=1)

x_train_transformed

array([[ 60.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  99.       ],
       [ 83.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  98.       ],
       [ 64.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       , 101.       ],
       [ 47.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       , 100.       ],
       [ 65.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  98.       ],
       [ 10.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       , 100.       ],
       [ 82.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       , 100.5890411],
       [ 47.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       , 101.       ],
       [ 51.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       , 101.       ],
       [  5.       ,   0.   

method 2: using column transform

In [56]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['city','gender']),
],remainder='passthrough')

In [60]:
transformer.fit_transform(x_train)

array([[ 99.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  60.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  83.       ],
       [101.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  65.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  10.       ],
       [100.5890411,   0.       ,   0.       ,   1.       ,   0.       ,
          1.       ,  82.       ],
       [101.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  47.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  51.       ],
       [102.       ,   0.   