multiple linear regression

In [1]:
import numpy as np 
import pandas as pd 
import plotly.express as px 
from sklearn.metrics import r2_score

In [2]:
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)
df=pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})
df.head(5)

feature1  feature2     target
0  0.180462  0.532912  47.045554
1  0.107294  0.881807 -74.803646
2 -1.455738 -1.408919  -4.154672
3  2.288525 -0.169957  37.522448
4 -1.112971 -1.059861 -86.284475

In [3]:
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,2],test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print('r2_score',r2_score(y_test,y_pred))

r2_score 0.795516242559539


In [ ]:
lr.coef_

array([19.145696 , 85.9500329])

In [ ]:
lr.intercept_

np.float64(0.7475518622132875)

part 3

In [6]:
from sklearn.datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [7]:
x.shape

(442, 10)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
x_train.shape

(353, 10)

In [26]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [27]:
# y_pred=reg.predict(x_test)
# print('r2_score',r2_score(y_test,y_pred))

In [28]:
reg.coef_,


(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),)

In [29]:
reg.intercept_

np.float64(151.88331005254167)

making our own linear regression class 

In [34]:
class meralr:
    def __init__(self):
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        # calculating the coffe
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.coef_=betas[1:]
        self.intercept_=betas[0]

    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_)+self.intercept_
        return y_pred

In [35]:
lr1=meralr()
lr1.fit(x_train,y_train)

In [36]:
y_pred=lr1.predict(x_test)
print('r2_score',r2_score(y_test,y_pred))

r2_score 0.43993386615689756
